// Mocks generated by Mockito 5.0.15 from annotations
// in todo_app_redux/test/redux/todo_middleware_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app_redux/data/model/todo.dart' as _i4;
import 'package:todo_app_redux/data/provider/uuid_provider.dart' as _i5;
import 'package:todo_app_redux/data/repository/todo_repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [AbstractTodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractTodoRepository extends _i1.Mock
    implements _i2.AbstractTodoRepository {
  MockAbstractTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> create(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#create, [todo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<List<_i4.Todo>> read() =>
      (super.noSuchMethod(Invocation.method(#read, []),
              returnValue: Future<List<_i4.Todo>>.value(<_i4.Todo>[]))
          as _i3.Future<List<_i4.Todo>>);
  @override
  _i3.Future<void> update(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#update, [todo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> delete(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#delete, [todo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AbstractUuidProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractUuidProvider extends _i1.Mock
    implements _i5.AbstractUuidProvider {
  MockAbstractUuidProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateUuid() =>
      (super.noSuchMethod(Invocation.method(#generateUuid, []), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}
